---
- name: Install Clickhouse
  hosts: clickhouse
  become: true

  roles:
    - clickhouse

  tasks:
    - name: Create logs database
      ansible.builtin.command: "clickhouse-client -q 'CREATE DATABASE IF NOT EXISTS logs'"
      register: create_db
      changed_when: create_db.rc == 0

- name: Install Vector
  hosts: vector
  become: true

  roles:
    - vector

- name: Install LightHouse
  hosts: lighthouse
  become: true

  roles:
    - lighthouse
